"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

export default function ReportsList() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/reports")
      .then(res => res.json())
      .then(data => {
        setReports(data.reports || []);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, []);

  return (
    <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
      <header className="flex-between" style={{ marginBottom: "3rem" }}>
        <div>
          <h1 style={{ fontSize: "2.5rem", fontWeight: "700", marginBottom: "0.5rem" }}>
            Offer Reports
          </h1>
          <p style={{ color: "var(--text-secondary)" }}>Detailed evaluations generated by your CLI.</p>
        </div>
      </header>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(350px, 1fr))", gap: "1.5rem" }}>
        {loading ? (
          <p style={{ color: "var(--text-secondary)" }}>Loading reports...</p>
        ) : reports.length === 0 ? (
          <p style={{ color: "var(--text-secondary)" }}>No reports found. Run a CLI evaluation to generate one.</p>
        ) : (
          reports.map(report => (
            <Link href={`/reports/${report.id}`} key={report.id}>
              <div className="glass-panel" style={{ padding: "1.5rem", height: "100%", transition: "transform 0.2s, box-shadow 0.2s" }} 
                   onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-4px)'; e.currentTarget.style.boxShadow = '0 10px 30px rgba(0,0,0,0.2)'; }}
                   onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 30px rgba(0, 0, 0, 0.1)'; }}>
                <div className="flex-between" style={{ marginBottom: "1rem" }}>
                  <span style={{ fontSize: "0.875rem", color: "var(--text-secondary)", fontFamily: "monospace" }}>{report.id}</span>
                  <span style={{ background: "rgba(99, 102, 241, 0.1)", color: "var(--accent-color)", padding: "0.25rem 0.5rem", borderRadius: "4px", fontSize: "0.875rem", fontWeight: "600" }}>
                    Score: {report.score}/5
                  </span>
                </div>
                <h3 style={{ fontSize: "1.25rem", fontWeight: "600", marginBottom: "0.5rem", color: "var(--text-primary)" }}>{report.title}</h3>
                <p style={{ color: "var(--text-secondary)", fontSize: "0.875rem", marginBottom: "1rem" }}>Archetype: {report.archetype}</p>
                <p style={{ color: "var(--text-secondary)", fontSize: "0.875rem" }}>Date: {report.date}</p>
              </div>
            </Link>
          ))
        )}
      </div>
    </div>
  );
}
